// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: minhdoan (https://sketchfab.com/minhdoan)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/avengers-logo-231231c2e94b48eba6566cd424193d42
// Title: Avengers Logo
// */

// import React, { useRef, useMemo, useContext, createContext } from 'react'
// import { useGLTF, Merged } from '@react-three/drei'

// const context = createContext()
// export function Instances({ children, ...props }) {
//     const { nodes } = useGLTF('/scene.gltf')
//     const instances = useMemo(
//         () => ({
//             BodySteelSatin: nodes['Body7_Steel_-_Satin_0'],
//             BodySteelSatin1: nodes['Body8_Steel_-_Satin_0'],
//             BodySteelSatin2: nodes['Body11_Steel_-_Satin_0'],
//             BodySteelSatin3: nodes['Body12_Steel_-_Satin_0'],
//             BodySteelSatin4: nodes['Body13_Steel_-_Satin_0'],
//             BodySteelSatin5: nodes['Body14_Steel_-_Satin_0'],
//             BodySteelSatin6: nodes['Body15_Steel_-_Satin_0'],
//             BodySteelSatin7: nodes['Body16_Steel_-_Satin_0'],
//             BodySteelSatin8: nodes['Body18_Steel_-_Satin_0'],
//             BodySteelSatin9: nodes['Body19_Steel_-_Satin_0'],
//             BodySteelSatin10: nodes['Body20_Steel_-_Satin_0'],
//             BodySteelSatin11: nodes['Body24_Steel_-_Satin_0'],
//             BodySteelSatin12: nodes['Body25_Steel_-_Satin_0'],
//             BodySteelSatin13: nodes['Body26_Steel_-_Satin_0'],
//             BodySteelSatin14: nodes['Body30_Steel_-_Satin_0'],
//             BodySteelSatin15: nodes['Body31_Steel_-_Satin_0'],
//             BodySteelSatin16: nodes['Body32_Steel_-_Satin_0'],
//             BodySteelSatin17: nodes['Body33_Steel_-_Satin_0'],
//             BodySteelSatin18: nodes['Body34_Steel_-_Satin_0'],
//         }),
//         [nodes]
//     )
//     return (
//         <Merged meshes={instances} {...props}>
//             {(instances) => <context.Provider value={instances} children={children} />}
//         </Merged>
//     )
// }

// export function Model(props) {
//     const instances = useContext(context)
//     return (
//         <group {...props} dispose={null}>
//             <group scale={0.001}>
//                 <instances.BodySteelSatin scale={10} />
//                 <instances.BodySteelSatin1 scale={10} />
//                 <instances.BodySteelSatin2 scale={10} />
//                 <instances.BodySteelSatin3 scale={10} />
//                 <instances.BodySteelSatin4 scale={10} />
//                 <instances.BodySteelSatin5 scale={10} />
//                 <instances.BodySteelSatin6 scale={10} />
//                 <instances.BodySteelSatin7 scale={10} />
//                 <instances.BodySteelSatin8 scale={10} />
//                 <instances.BodySteelSatin9 scale={10} />
//                 <instances.BodySteelSatin10 scale={10} />
//                 <instances.BodySteelSatin11 scale={10} />
//                 <instances.BodySteelSatin12 scale={10} />
//                 <instances.BodySteelSatin13 scale={10} />
//                 <instances.BodySteelSatin14 scale={10} />
//                 <instances.BodySteelSatin15 scale={10} />
//                 <instances.BodySteelSatin16 scale={10} />
//                 <instances.BodySteelSatin17 scale={10} />
//                 <instances.BodySteelSatin18 scale={10} />
//             </group>
//         </group>
//     )
// }

// useGLTF.preload('/scene.gltf')
